<?php
/**
 * @file
 * tmi_scholarship.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function tmi_scholarship_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-scholarship-field_application_form'
  $field_instances['node-scholarship-field_application_form'] = array(
    'bundle' => 'scholarship',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select the Application Form for Applicants to submit.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_application_form',
    'label' => 'Application Form',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-scholarship-field_date_application'
  $field_instances['node-scholarship-field_date_application'] = array(
    'bundle' => 'scholarship',
    'deleted' => 0,
    'description' => 'Set the date range for when the Application Form is accessible.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'date',
        'settings' => array(
          'format_type' => 'long',
          'fromto' => 'both',
          'multiple_from' => '',
          'multiple_number' => '',
          'multiple_to' => '',
        ),
        'type' => 'date_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_date_application',
    'label' => 'Application Dates',
    'required' => 1,
    'settings' => array(
      'default_value' => 'now',
      'default_value2' => 'same',
      'default_value_code' => '',
      'default_value_code2' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'date',
      'settings' => array(
        'increment' => 15,
        'input_format' => 'm/d/Y - H:i:s',
        'input_format_custom' => '',
        'label_position' => 'above',
        'text_parts' => array(),
        'year_range' => '-3:+3',
      ),
      'type' => 'date_text',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-scholarship-field_recommend_form_optional'
  $field_instances['node-scholarship-field_recommend_form_optional'] = array(
    'bundle' => 'scholarship',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select the Recommendation Form to use for optional Recommendations, if applicable.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_recommend_form_optional',
    'label' => 'Optional Recommendation Form',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-scholarship-field_recommend_form_required'
  $field_instances['node-scholarship-field_recommend_form_required'] = array(
    'bundle' => 'scholarship',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select the Recommendation Form node to use for required Recommendations.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_recommend_form_required',
    'label' => 'Required Recommendation Form',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Application Dates');
  t('Application Form');
  t('Optional Recommendation Form');
  t('Required Recommendation Form');
  t('Select the Application Form for Applicants to submit.');
  t('Select the Recommendation Form node to use for required Recommendations.');
  t('Select the Recommendation Form to use for optional Recommendations, if applicable.');
  t('Set the date range for when the Application Form is accessible.');

  return $field_instances;
}
