<?php

/**
 * Implements hook_user_user_insert().
 */
function tmi_user_user_insert(&$edit, $account, $category) {
  // Sanity check.
  if (!module_exists('tmi_application')) {
    return;
  }

  // If this user has access to review applications, they are not an applicant.
  if (user_access('review applications')) {
    return;
  }
  // Create an Application entity for the active Scholarship for this applicant.
  $application = entity_create('application', array(
    'uid' => $account->uid,
    'nid_apply_for' => TMI_SCHOLARSHIP_NID,
    'nid_application_form' => TMI_APPLICATION_FORM_NID,
    'submitted' => NULL,
    'completed' => NULL,
  ));
  // Save the Application entity.
  $application->save();
}
