<?php
/**
 * @file
 * Code for the tmi_scholarship_application module.
 */

/**
 * Implements hook_entity_info().
 */
function tmi_application_entity_info() {
  $info = array();
  $info['application'] = array(
    'label' => t('Application'),
    'base table' => 'tmi_application',
    'entity keys' => array(
      'id' => 'aid',
      'label' => 'aid',
    ),
    'entity class' => 'ApplicationEntity',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'ApplicationEntityController',
    'module' => 'tmi_application',
  );
  return $info;
}

/**
 * Implements hook_menu().
 */
function tmi_application_menu() {
  $items['application'] = array(
    'page callback' => 'tmi_application_page',
    'access arguments' => array('access content'),
  );
  $items['application/%application'] = array(
    'title' => 'Application',
    'page callback' => 'tmi_application_view_application_page',
    'page arguments' => array(1),
    'access callback' => 'tmi_application_review_page_access'
  );
  return $items;
}


/**
 * Implements hook_theme().
 */
function tmi_application_theme($existing, $type, $theme, $path) {
  return array(
    'application' => array(
      'template' => 'application',
      'path' => drupal_get_path('module', 'tmi_application') . '/theme',
    ),
    'application_status' => array(
      'template' => 'application-status',
      'path' => drupal_get_path('module', 'tmi_application') . '/theme',
    ),
  );
}

/**
 * Menu autoloader for %application.
 */
function application_load($aid) {
  return entity_load_single('application', $aid);
}

/**
 * Access callback for Application Review page.
 */
function tmi_application_review_page_access() {
  return user_access('administer modules');
}

/**
 * Retrieve the Application aid for the current user.
 */
function tmi_application_get_application_aid($uid = NULL) {
  if (!$uid) {
    global $user;
    $uid = $user->uid;
  } 
  return db_select("tmi_application", "a")
    ->fields("a", array("aid"))
    ->condition("uid", $uid)
    ->execute()
    ->fetchField();
}

function tmi_application_page() {
  if (!user_is_logged_in()) {
    return t("Please login.");
  }

  // Load the Scholarship webform node.
  $node = node_load(TMI_SCHOLARSHIP_NID);
  // Load its webform, which is the Scholarship application.
  webform_node_view($node, 'full');
  $content = isset($node->content['webform']) ? $node->content['webform'] : array();
  // If a webform exists:
  if ($output = theme_webform_view($node->content)) {
    // Return it.
    return $output;
  }

  // If we've made it this far, the webform has been submitted.
  return tmi_application_status_page();

}

/**
 * Returns HTML for the Application status page.
 */
function tmi_application_status_page() {
  $aid = tmi_application_get_application_aid();
  $application = entity_load_single('application', $aid);
  $admin = user_access('administer modules');

  return theme('application_status', array(
    'application' => $application,
    'recommendations' => tmi_recommendation_get_recommendations_table($aid, $admin),
    'request_form' => drupal_get_form('tmi_recommendation_request_form', $aid),
  ));
}

/**
 * Implements hook_webform_submission_insert().
 */
function tmi_application_webform_submission_insert($node, $submission) {
  // If this was the Scholarship application:
  if ($node->nid == TMI_SCHOLARSHIP_NID) {
    // Get the uid of the user who submitted it.
    $uid = $submission->uid;
    // Get the User's Application aid.
    $aid = tmi_application_get_application_aid($uid);
    // Set the application as completed with the new $sid.
    $application = entity_load_single('application', $aid);
    $application->submitted($submission->sid);
  }
}

/**
 * Page callback for the Application Review page.
 */
function tmi_application_view_application_page($application) {
  return $application->view();
}
