<?php
/**
 * @file
 * Code for the tmi_recommend_form feature.
 */

include_once 'tmi_recommend_form.features.inc';

// hardcode for now.
define('TMI_RECOMMEND_FORM_NID', 4);

/**
 * Implements hook_node_view().
 */
function tmi_recommend_form_node_view($node, $view_mode, $langcode) {
  if ($node->type != 'recommend_form') {
    return;
  }

  // Make sure an Recommendation rid has been passed into the URL.
  if (isset($_GET['rid'])) {
    // @todo: Decrypt passed value.
    $rid = $_GET['rid'];
    // @todo: Check if the Recommendation has been submitted.  If so, no form.
  }

  // Else if no 'rid' found in the query string:
  else {
    // Remove all content.
    unset($node->content);
    // Display error message.
    $node->content['error'] = array(
      '#markup' => t("Invalid URL.  Please check the email sent."),
    );
  }
}

